apiVersion: apps/v1
kind: Deployment
metadata:
  name: ghost
  labels:
    app: ghost
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ghost
  template:
    metadata:
      labels:
        app: ghost
    spec:
      containers:
        - name: ghost
          image: ghost:4-alpine
          ports:
            - containerPort: 8080
          env:
            - name: database__client
              value: "mysql"
            - name: database__connection__host
              value: "db"
            - name: database__connection__user
              value: "root"
            - name: database__connection__password
              value: "replaceme"
            - name: database__connection__database
              value: "ghost"
